### ISSUE TITLE
[POLYGON] AAVE Leveraged

### ISSUE THREAD

**Issue by saltyfacu** [MVPWorkshop/tesseract-vaults#8]
## Claiming a strategy

**Protocol name**: AAVE

**Brief Strategy Description**: Levered strat using AAVE

## Due Diligence Review

**Protocol Due Diligence and Path to Prod**: 

## Strategy Review

**Description**: 

**Commit (hash)**: 

**Tag**:

**Repo**: https://github.com/MVPWorkshop/tesseract-vaults

**Scope**: (List link to files)
- [contracts/strategies/StrategyLeveragedAAVE.sol](https://github.com/MVPWorkshop/tesseract-vaults/blob/master/contracts/strategies/StrategyLeveragedAAVE.sol)

**Additional References or Repo** (Link to underlying protocols or relevant documents):
- PR with review: https://github.com/MVPWorkshop/tesseract-vaults/pull/7
- Based on this strategy: https://github.com/GalloDaSballo/wbtc-levered-strat/releases/tag/Ape.0.1
- Original ticket: https://github.com/yearn/yearn-strategies/issues/114

**Deployed Contract** (etherscan link): 
LeveragedAAVE Strategy:
 ⁃ USDC: [0x4e88B4f358406b5cd36622771Fd427d719f6f5fC](https://polygonscan.com/address/0x4e88B4f358406b5cd36622771Fd427d719f6f5fC)
 ⁃ DAI: [0xEbB24DAACC8e5CE6c137Aa64c55a3e7cFa0FBF4D](https://polygonscan.com/address/0x4e88B4f358406b5cd36622771Fd427d719f6f5fC)
 ⁃ USDT: [0x09bf4D210dC9d95A1115443DEd3554eeF48a10E9](https://polygonscan.com/address/0x4e88B4f358406b5cd36622771Fd427d719f6f5fC)
 ⁃ WBTC: [0x5Dd3b8f3141186B5bAfAFbaD9cBf26ffC6116C91](https://polygonscan.com/address/0x4e88B4f358406b5cd36622771Fd427d719f6f5fC)
 ⁃ WETH: [0xcf26db4f3bB6b75E2E7222676931E815D465195C](https://polygonscan.com/address/0x4e88B4f358406b5cd36622771Fd427d719f6f5fC)

**Review Ongoing By**:
- [ ] @storming0x 
- [ ] @salazarguille 

**Review Completed By**:
- [ ] @storming0x 
- [ ] @salazarguille

**Comment by storming0x** [comment]
Recommendation:

Aave code has been updated as per @fp-crypto latest codebase that doesn't present the issue.

Update constructor init logic to handle the case for not using flashloans as default since that generated a bit of manual operations in current Polygon system.
